# Generated by Django 3.1.3 on 2020-11-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user',
            new_name='author',
        ),
    ]
